name: "Pipe Terraform"

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  terraform:
      uses: "yagoalmeida/cicd_tf_centralizado/.github/workflows/terraform_centralizado.yaml@main"
      with:
        tf_version: "1.0.9"
        os_version: "ubuntu-20.04"
        use_state_bucket: true
        bucket_name: "shared-storage-terraform-state-dev"
        key_tf_state: "yagoalmeida/poc_lambda_iac_terraform"
      secrets:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
